# EDA for the DMEPOS by Referring Provider (No Service)

This script uses the DMEPOS_rfrr_clean.csv and leie_with_valid_npi_clean.csv  to create summary stats and scatter plots.

This script creates the "DMEPOS_rfrr_clean_labeled.csv"

In [1]:
import pandas as pd

df = pd.read_csv('/dsa/groups/casestudycf25/team02/DMEPOS_rfrr_clean.csv',dtype={'Rfrg_Prvdr_State_FIPS':str,'Rfrg_Prvdr_Zip5':str}) # ensure Rfrg_Prvdr_State_FIPS & Rfrg_Prvdr_Zip5 are imported as str
df.head()

,Rfrg_NPI,Rfrg_Prvdr_Last_Name_Org,Rfrg_Prvdr_First_Name,Rfrg_Prvdr_MI,Rfrg_Prvdr_Crdntls,Rfrg_Prvdr_Ent_Cd,Rfrg_Prvdr_St1,Rfrg_Prvdr_St2,Rfrg_Prvdr_City,Rfrg_Prvdr_State_Abrvtn,...,Bene_CC_PH_HF_NonIHD_V2_Pct,Bene_CC_PH_Hyperlipidemia_V2_Pct,Bene_CC_PH_Hypertension_V2_Pct,Bene_CC_PH_IschemicHeart_V2_Pct,Bene_CC_PH_Osteoporosis_V2_Pct,Bene_CC_PH_Parkinson_V2_Pct,Bene_CC_PH_Arthritis_V2_Pct,Bene_CC_PH_Stroke_TIA_V2_Pct,Bene_Avg_Risk_Scre,Year
0,1003000126,Enkeshafi,Ardalan,NaN,md,I,6410 Rockledge Dr Ste 304,NaN,Bethesda,MD,...,0.0,0.000000,1.000000,0.0,0.0,0.0,0.0,0.0,1.942167,2021
1,1003000480,Rothchild,Kevin,B,md,I,12605 E 16th Ave,NaN,Aurora,CO,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,2.278200,2021
2,1003000522,Weigand,Frederick,J,md,I,1565 Saxon Blvd,Suite 102,Deltona,FL,...,0.0,1.000000,0.846154,0.0,0.0,0.0,0.0,0.0,1.872308,2021
3,1003000530,Semonche,Amanda,M,do,I,1021 Park Ave,Suite 203,Quakertown,PA,...,0.0,0.833333,0.777778,0.0,0.0,0.0,0.0,0.0,2.144684,2021
4,1003000597,Kim,Dae,Y,mdphd,I,1145 S Utica Ave,Suite 202,Tulsa,OK,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,2.006500,2021

In [2]:
labs = pd.read_csv('/dsa/groups/casestudycf25/team02/leie_with_valid_npi_clean.csv',dtype={'npi':int}) # make sure npi numbers are read as int
labs['EXCLDATE'] = labs.excldate.apply(lambda x: int(x[:4]))
labs = labs[['npi','fraud_flag','EXCLDATE']]
labs.head()

          npi  fraud_flag  EXCLDATE
0  1861529091           1      2024
1  1366544512           1      2021
2  1376214585           1      2025
3  1326353459           1      2022
4  1578130340           1      2025

In [3]:
# merge labs w/ df on npi, retain all NPIs in df
df = pd.merge(labs, df, how='right', left_on='npi', right_on='Rfrg_NPI')
df.head()

,npi,fraud_flag,EXCLDATE,Rfrg_NPI,Rfrg_Prvdr_Last_Name_Org,Rfrg_Prvdr_First_Name,Rfrg_Prvdr_MI,Rfrg_Prvdr_Crdntls,Rfrg_Prvdr_Ent_Cd,Rfrg_Prvdr_St1,...,Bene_CC_PH_HF_NonIHD_V2_Pct,Bene_CC_PH_Hyperlipidemia_V2_Pct,Bene_CC_PH_Hypertension_V2_Pct,Bene_CC_PH_IschemicHeart_V2_Pct,Bene_CC_PH_Osteoporosis_V2_Pct,Bene_CC_PH_Parkinson_V2_Pct,Bene_CC_PH_Arthritis_V2_Pct,Bene_CC_PH_Stroke_TIA_V2_Pct,Bene_Avg_Risk_Scre,Year
0,1.972597e+09,1.0,2023.0,1972596757,Naushad,Abdul,N,md,I,2865 James Blvd,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,1.255375,2021
1,1.265697e+09,1.0,2024.0,1265697478,Balger,Abigail,NaN,md,I,805 E Geneva Dr,...,0.000000,0.735294,0.794118,0.000000,0.0,0.0,0.529412,0.0,1.433834,2021
2,1.922096e+09,1.0,2024.0,1922096221,Alperovich,Alexander,NaN,md,I,1340 Union University Dr,...,0.666667,0.878788,0.969697,0.727273,0.0,0.0,0.666667,0.0,1.858711,2021
3,1.922096e+09,1.0,2024.0,1922096221,Alperovich,Alexander,NaN,md,I,1340 Union University Dr,...,0.608696,0.913043,1.000000,0.739130,0.0,0.0,0.695652,0.0,1.658419,2022
4,1.922096e+09,1.0,2024.0,1922096221,Alperovich,Alexander,NaN,md,I,1340 Union University Dr,...,0.000000,0.944444,1.000000,0.611111,0.0,0.0,0.000000,0.0,1.766700,2023

In [4]:
# impute missing values
df['npi'] = df['npi'].fillna(df['Rfrg_NPI'].astype(int))
df['fraud_flag'] = df['fraud_flag'].fillna(0)
df['EXCLDATE'] = df['EXCLDATE'].fillna(0)
# change npi to integer type
df['npi'] = df.npi.astype(int)

df.head()

,npi,fraud_flag,EXCLDATE,Rfrg_NPI,Rfrg_Prvdr_Last_Name_Org,Rfrg_Prvdr_First_Name,Rfrg_Prvdr_MI,Rfrg_Prvdr_Crdntls,Rfrg_Prvdr_Ent_Cd,Rfrg_Prvdr_St1,...,Bene_CC_PH_HF_NonIHD_V2_Pct,Bene_CC_PH_Hyperlipidemia_V2_Pct,Bene_CC_PH_Hypertension_V2_Pct,Bene_CC_PH_IschemicHeart_V2_Pct,Bene_CC_PH_Osteoporosis_V2_Pct,Bene_CC_PH_Parkinson_V2_Pct,Bene_CC_PH_Arthritis_V2_Pct,Bene_CC_PH_Stroke_TIA_V2_Pct,Bene_Avg_Risk_Scre,Year
0,1972596757,1.0,2023.0,1972596757,Naushad,Abdul,N,md,I,2865 James Blvd,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,1.255375,2021
1,1265697478,1.0,2024.0,1265697478,Balger,Abigail,NaN,md,I,805 E Geneva Dr,...,0.000000,0.735294,0.794118,0.000000,0.0,0.0,0.529412,0.0,1.433834,2021
2,1922096221,1.0,2024.0,1922096221,Alperovich,Alexander,NaN,md,I,1340 Union University Dr,...,0.666667,0.878788,0.969697,0.727273,0.0,0.0,0.666667,0.0,1.858711,2021
3,1922096221,1.0,2024.0,1922096221,Alperovich,Alexander,NaN,md,I,1340 Union University Dr,...,0.608696,0.913043,1.000000,0.739130,0.0,0.0,0.695652,0.0,1.658419,2022
4,1922096221,1.0,2024.0,1922096221,Alperovich,Alexander,NaN,md,I,1340 Union University Dr,...,0.000000,0.944444,1.000000,0.611111,0.0,0.0,0.000000,0.0,1.766700,2023

In [5]:
def make_labels(fraud_flag, start_exc, data_yr):
    if start_exc >= data_yr:
        return fraud_flag
    else:
        return 0

df['target'] = df[['fraud_flag','EXCLDATE','Year']].apply(lambda x: make_labels(*x), axis=1)
df.head()

,npi,fraud_flag,EXCLDATE,Rfrg_NPI,Rfrg_Prvdr_Last_Name_Org,Rfrg_Prvdr_First_Name,Rfrg_Prvdr_MI,Rfrg_Prvdr_Crdntls,Rfrg_Prvdr_Ent_Cd,Rfrg_Prvdr_St1,...,Bene_CC_PH_Hyperlipidemia_V2_Pct,Bene_CC_PH_Hypertension_V2_Pct,Bene_CC_PH_IschemicHeart_V2_Pct,Bene_CC_PH_Osteoporosis_V2_Pct,Bene_CC_PH_Parkinson_V2_Pct,Bene_CC_PH_Arthritis_V2_Pct,Bene_CC_PH_Stroke_TIA_V2_Pct,Bene_Avg_Risk_Scre,Year,target
0,1972596757,1.0,2023.0,1972596757,Naushad,Abdul,N,md,I,2865 James Blvd,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,1.255375,2021,1.0
1,1265697478,1.0,2024.0,1265697478,Balger,Abigail,NaN,md,I,805 E Geneva Dr,...,0.735294,0.794118,0.000000,0.0,0.0,0.529412,0.0,1.433834,2021,1.0
2,1922096221,1.0,2024.0,1922096221,Alperovich,Alexander,NaN,md,I,1340 Union University Dr,...,0.878788,0.969697,0.727273,0.0,0.0,0.666667,0.0,1.858711,2021,1.0
3,1922096221,1.0,2024.0,1922096221,Alperovich,Alexander,NaN,md,I,1340 Union University Dr,...,0.913043,1.000000,0.739130,0.0,0.0,0.695652,0.0,1.658419,2022,1.0
4,1922096221,1.0,2024.0,1922096221,Alperovich,Alexander,NaN,md,I,1340 Union University Dr,...,0.944444,1.000000,0.611111,0.0,0.0,0.000000,0.0,1.766700,2023,1.0

In [6]:
# convert target to int and drop unnecessary cols
df = df.drop(['fraud_flag','EXCLDATE','Rfrg_NPI'], axis=1)
df['target'] = df.target.astype(int)

# save as csv
df.to_csv('/dsa/groups/casestudycf25/team02/DMEPOS_rfrr_clean_labeled.csv')

df.head()

,npi,Rfrg_Prvdr_Last_Name_Org,Rfrg_Prvdr_First_Name,Rfrg_Prvdr_MI,Rfrg_Prvdr_Crdntls,Rfrg_Prvdr_Ent_Cd,Rfrg_Prvdr_St1,Rfrg_Prvdr_St2,Rfrg_Prvdr_City,Rfrg_Prvdr_State_Abrvtn,...,Bene_CC_PH_Hyperlipidemia_V2_Pct,Bene_CC_PH_Hypertension_V2_Pct,Bene_CC_PH_IschemicHeart_V2_Pct,Bene_CC_PH_Osteoporosis_V2_Pct,Bene_CC_PH_Parkinson_V2_Pct,Bene_CC_PH_Arthritis_V2_Pct,Bene_CC_PH_Stroke_TIA_V2_Pct,Bene_Avg_Risk_Scre,Year,target
0,1972596757,Naushad,Abdul,N,md,I,2865 James Blvd,NaN,Poplar Bluff,MO,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,1.255375,2021,1
1,1265697478,Balger,Abigail,NaN,md,I,805 E Geneva Dr,NaN,Dewitt,MI,...,0.735294,0.794118,0.000000,0.0,0.0,0.529412,0.0,1.433834,2021,1
2,1922096221,Alperovich,Alexander,NaN,md,I,1340 Union University Dr,NaN,Jackson,TN,...,0.878788,0.969697,0.727273,0.0,0.0,0.666667,0.0,1.858711,2021,1
3,1922096221,Alperovich,Alexander,NaN,md,I,1340 Union University Dr,NaN,Jackson,TN,...,0.913043,1.000000,0.739130,0.0,0.0,0.695652,0.0,1.658419,2022,1
4,1922096221,Alperovich,Alexander,NaN,md,I,1340 Union University Dr,NaN,Jackson,TN,...,0.944444,1.000000,0.611111,0.0,0.0,0.000000,0.0,1.766700,2023,1

In [7]:
# display summary stats
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:,.2f}'.format 

df.iloc[:,17:-2].describe()

,Tot_Suplrs,Tot_Suplr_HCPCS_Cds,Tot_Suplr_Benes,Tot_Suplr_Clms,Tot_Suplr_Srvcs,Suplr_Sbmtd_Chrgs,Suplr_Mdcr_Alowd_Amt,Suplr_Mdcr_Pymt_Amt,Suplr_Mdcr_Stdzd_Pymt_Amt,DME_Tot_Suplrs,DME_Tot_Suplr_HCPCS_Cds,DME_Tot_Suplr_Benes,DME_Tot_Suplr_Clms,DME_Tot_Suplr_Srvcs,DME_Suplr_Sbmtd_Chrgs,DME_Suplr_Mdcr_Alowd_Amt,DME_Suplr_Mdcr_Pymt_Amt,DME_Suplr_Mdcr_Stdzd_Pymt_Amt,POS_Tot_Suplrs,POS_Tot_Suplr_HCPCS_Cds,POS_Tot_Suplr_Benes,POS_Tot_Suplr_Clms,POS_Tot_Suplr_Srvcs,POS_Suplr_Sbmtd_Chrgs,POS_Suplr_Mdcr_Alowd_Amt,POS_Suplr_Mdcr_Pymt_Amt,POS_Suplr_Mdcr_Stdzd_Pymt_Amt,Drug_Tot_Suplrs,Drug_Tot_Suplr_HCPCS_Cds,Drug_Tot_Suplr_Benes,Drug_Tot_Suplr_Clms,Drug_Tot_Suplr_Srvcs,Drug_Suplr_Sbmtd_Chrgs,Drug_Suplr_Mdcr_Alowd_Amt,Drug_Suplr_Mdcr_Pymt_Amt,Drug_Suplr_Mdcr_Stdzd_Pymt_Amt,Bene_Avg_Age,Bene_Age_LT_65_Cnt,Bene_Age_65_74_Cnt,Bene_Age_75_84_Cnt,Bene_Age_GT_84_Cnt,Bene_Feml_Cnt,Bene_Male_Cnt,Bene_Race_Wht_Cnt,Bene_Race_Black_Cnt,Bene_Race_Api_Cnt,Bene_Race_Hspnc_Cnt,Bene_Race_Natind_Cnt,Bene_Race_Othr_Cnt,Bene_Ndual_Cnt,Bene_Dual_Cnt,Bene_CC_BH_ADHD_OthCD_V1_Pct,Bene_CC_BH_Alcohol_Drug_V1_Pct,Bene_CC_BH_Tobacco_V1_Pct,Bene_CC_BH_Alz_NonAlzdem_V2_Pct,Bene_CC_BH_Anxiety_V1_Pct,Bene_CC_BH_Bipolar_V1_Pct,Bene_CC_BH_Mood_V2_Pct,Bene_CC_BH_Depress_V1_Pct,Bene_CC_BH_PD_V1_Pct,Bene_CC_BH_PTSD_V1_Pct,Bene_CC_BH_Schizo_OthPsy_V1_Pct,Bene_CC_PH_Asthma_V2_Pct,Bene_CC_PH_Afib_V2_Pct,Bene_CC_PH_Cancer6_V2_Pct,Bene_CC_PH_CKD_V2_Pct,Bene_CC_PH_COPD_V2_Pct,Bene_CC_PH_Diabetes_V2_Pct,Bene_CC_PH_HF_NonIHD_V2_Pct,Bene_CC_PH_Hyperlipidemia_V2_Pct,Bene_CC_PH_Hypertension_V2_Pct,Bene_CC_PH_IschemicHeart_V2_Pct,Bene_CC_PH_Osteoporosis_V2_Pct,Bene_CC_PH_Parkinson_V2_Pct,Bene_CC_PH_Arthritis_V2_Pct,Bene_CC_PH_Stroke_TIA_V2_Pct,Bene_Avg_Risk_Scre
count,"1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00","1,157,253.00"
mean,10.57,19.94,26.39,120.01,"6,108.37","84,826.68","32,475.57","25,040.93","25,438.94",8.95,14.30,20.87,103.65,584.84,"48,321.40","16,735.57","12,754.10","13,050.61",0.82,2.20,4.04,7.86,807.65,"10,008.89","7,644.05","5,948.20","6,061.46",0.50,0.28,0.52,3.64,"1,998.33","3,724.96","1,514.19","1,188.07","1,175.11",72.66,1.07,8.11,6.06,1.11,9.66,8.71,18.86,1.05,0.24,0.66,0.02,0.13,9.50,2.91,0.00,0.00,0.01,0.01,0.06,0.00,0.07,0.06,0.00,0.00,0.00,0.01,0.04,0.02,0.09,0.06,0.22,0.06,0.38,0.42,0.09,0.02,0.00,0.19,0.01,1.97
std,11.53,18.11,57.99,290.68,"40,832.95","320,457.46","142,039.94","111,092.30","112,060.57",10.38,13.19,52.14,273.32,"2,384.17","160,826.12","68,933.92","53,497.46","54,221.04",2.17,5.92,24.79,33.73,"10,744.76","110,824.33","100,332.26","78,520.46","79,629.88",2.65,1.13,4.88,26.76,"29,455.68","47,421.22","27,604.73","21,783.56","21,541.40",6.63,7.14,26.85,23.86,7.30,31.38,29.63,50.00,7.03,3.56,5.89,0.78,1.78,49.25,12.31,0.00,0.03,0.05,0.07,0.14,0.02,0.16,0.14,0.01,0.00,0.02,0.06,0.11,0.09,0.19,0.16,0.32,0.14,0.41,0.43,0.18,0.06,0.01,0.29,0.04,1.09
min,1.00,1.00,5.00,11.00,11.00,46.75,1.21,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,3.00,8.00,5.00,21.00,74.00,"8,179.96","3,033.77","2,274.40","2,393.61",3.00,6.00,5.00,19.00,43.00,"5,728.86","1,846.06","1,367.54","1,465.72",0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,70.07,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.28
50%,6.00,14.00,13.00,44.00,522.00,"22,270.97","8,154.20","6,185.31","6,373.54",5.00,10.00,5.00,32.00,86.00,"11,007.16","3,548.50","2,655.64","2,796.77",0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,73.33,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.73
75%,13.00,27.00,27.00,105.00,"2,797.00","62,731.94","23,482.15","17,985.21","18,210.09",11.00,20.00,20.00,86.00,343.00,"36,703.23","12,519.53","9,486.74","9,721.26",0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,76.21,0.00,11.00,0.00,0.00,0.00,0.00,22.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.50,0.00,0.81,0.87,0.00,0.00,0.00,0.47,0.00,2.35
max,240.00,289.00,"8,179.00","19,877.00","5,599,029.00","69,737,140.32","19,669,167.15","15,481,688.16","14,793,909.20",226.00,177.00,"8,179.00","19,877.00","592,878.00","40,173,684.59","19,669,167.15","15,481,688.16","14,793,909.20",58.00,177.00,"7,786.00","7,897.00","595,678.00","13,543,621.05","10,118,051.82","7,890,551.74","8,060,083.23",193.00,14.00,415.00,"3,072.00","5,580,547.00","7,064,075.30","6,062,734.10","4,699,145.16","4,622,622.62",109.00,989.00,"2,739.00","4,442.00","1,882.00","5,168.00","3,528.00","6,817.00","1,478.00",394.00,717.00,170.00,188.00,"7,612.00","2,412.00",0.94,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.96,0.87,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,28.27

In [11]:
# summary stats for fraud class
df_fraud = df[df.target==1]

df_fraud.iloc[:,17:-2].describe()

,Tot_Suplrs,Tot_Suplr_HCPCS_Cds,Tot_Suplr_Benes,Tot_Suplr_Clms,Tot_Suplr_Srvcs,Suplr_Sbmtd_Chrgs,Suplr_Mdcr_Alowd_Amt,Suplr_Mdcr_Pymt_Amt,Suplr_Mdcr_Stdzd_Pymt_Amt,DME_Tot_Suplrs,DME_Tot_Suplr_HCPCS_Cds,DME_Tot_Suplr_Benes,DME_Tot_Suplr_Clms,DME_Tot_Suplr_Srvcs,DME_Suplr_Sbmtd_Chrgs,DME_Suplr_Mdcr_Alowd_Amt,DME_Suplr_Mdcr_Pymt_Amt,DME_Suplr_Mdcr_Stdzd_Pymt_Amt,POS_Tot_Suplrs,POS_Tot_Suplr_HCPCS_Cds,POS_Tot_Suplr_Benes,POS_Tot_Suplr_Clms,POS_Tot_Suplr_Srvcs,POS_Suplr_Sbmtd_Chrgs,POS_Suplr_Mdcr_Alowd_Amt,POS_Suplr_Mdcr_Pymt_Amt,POS_Suplr_Mdcr_Stdzd_Pymt_Amt,Drug_Tot_Suplrs,Drug_Tot_Suplr_HCPCS_Cds,Drug_Tot_Suplr_Benes,Drug_Tot_Suplr_Clms,Drug_Tot_Suplr_Srvcs,Drug_Suplr_Sbmtd_Chrgs,Drug_Suplr_Mdcr_Alowd_Amt,Drug_Suplr_Mdcr_Pymt_Amt,Drug_Suplr_Mdcr_Stdzd_Pymt_Amt,Bene_Avg_Age,Bene_Age_LT_65_Cnt,Bene_Age_65_74_Cnt,Bene_Age_75_84_Cnt,Bene_Age_GT_84_Cnt,Bene_Feml_Cnt,Bene_Male_Cnt,Bene_Race_Wht_Cnt,Bene_Race_Black_Cnt,Bene_Race_Api_Cnt,Bene_Race_Hspnc_Cnt,Bene_Race_Natind_Cnt,Bene_Race_Othr_Cnt,Bene_Ndual_Cnt,Bene_Dual_Cnt,Bene_CC_BH_ADHD_OthCD_V1_Pct,Bene_CC_BH_Alcohol_Drug_V1_Pct,Bene_CC_BH_Tobacco_V1_Pct,Bene_CC_BH_Alz_NonAlzdem_V2_Pct,Bene_CC_BH_Anxiety_V1_Pct,Bene_CC_BH_Bipolar_V1_Pct,Bene_CC_BH_Mood_V2_Pct,Bene_CC_BH_Depress_V1_Pct,Bene_CC_BH_PD_V1_Pct,Bene_CC_BH_PTSD_V1_Pct,Bene_CC_BH_Schizo_OthPsy_V1_Pct,Bene_CC_PH_Asthma_V2_Pct,Bene_CC_PH_Afib_V2_Pct,Bene_CC_PH_Cancer6_V2_Pct,Bene_CC_PH_CKD_V2_Pct,Bene_CC_PH_COPD_V2_Pct,Bene_CC_PH_Diabetes_V2_Pct,Bene_CC_PH_HF_NonIHD_V2_Pct,Bene_CC_PH_Hyperlipidemia_V2_Pct,Bene_CC_PH_Hypertension_V2_Pct,Bene_CC_PH_IschemicHeart_V2_Pct,Bene_CC_PH_Osteoporosis_V2_Pct,Bene_CC_PH_Parkinson_V2_Pct,Bene_CC_PH_Arthritis_V2_Pct,Bene_CC_PH_Stroke_TIA_V2_Pct,Bene_Avg_Risk_Scre
count,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00,253.00
mean,15.22,27.99,95.68,241.62,"5,501.60","262,353.00","169,442.46","131,093.12","130,161.40",12.23,19.41,30.89,157.39,"1,265.66","59,064.52","23,725.91","18,089.87","18,474.44",2.38,4.34,64.15,78.77,503.28,"178,648.67","139,409.93","108,065.58","106,701.61",0.77,0.42,0.76,5.45,"1,195.12","1,606.43",465.83,360.40,353.61,72.65,9.04,35.75,35.98,5.25,53.32,35.43,67.58,12.68,1.97,5.01,0.54,1.69,59.12,27.74,0.00,0.01,0.03,0.04,0.10,0.01,0.11,0.09,0.00,0.00,0.01,0.03,0.05,0.02,0.11,0.10,0.29,0.11,0.39,0.46,0.15,0.03,0.00,0.27,0.02,2.03
std,18.63,30.49,456.49,637.00,"12,599.47","1,318,991.26","1,033,359.67","800,757.54","794,113.95",16.32,20.21,61.95,372.72,"5,068.83","115,831.46","51,622.92","39,764.43","40,604.11",6.73,9.84,455.73,526.84,"1,949.57","1,318,350.74","1,035,029.34","802,031.73","795,365.56",2.42,1.19,3.50,19.16,"5,907.98","7,555.18","2,971.04","2,341.81","2,295.13",5.89,50.09,199.80,204.64,16.68,281.17,176.84,358.42,63.95,12.15,24.78,3.50,11.33,342.01,121.36,0.00,0.05,0.08,0.11,0.18,0.04,0.20,0.18,0.01,0.00,0.05,0.08,0.10,0.06,0.19,0.18,0.36,0.18,0.41,0.45,0.22,0.10,0.01,0.33,0.07,0.78
min,1.00,1.00,5.00,11.00,12.00,503.84,105.52,28.32,69.70,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,51.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.63
25%,4.00,8.00,5.00,20.00,75.00,"7,702.58","3,219.32","2,558.82","2,491.93",3.00,6.00,5.00,19.00,40.00,"4,313.56","1,707.05","1,233.45","1,243.09",0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,68.91,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.45
50%,8.00,16.00,13.00,45.00,662.00,"32,290.88","10,217.71","7,784.70","8,243.43",6.00,12.00,5.00,39.00,103.00,"13,453.90","4,152.08","3,173.42","3,413.64",0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,72.78,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.61,0.00,0.00,0.00,0.00,0.00,1.99
75%,18.00,32.00,36.00,156.00,"5,599.00","99,652.46","41,127.92","30,625.39","29,893.07",13.00,25.00,27.00,116.00,523.00,"50,889.55","20,342.29","15,899.89","14,396.99",1.00,2.00,0.00,11.00,15.00,908.04,669.60,535.68,582.36,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,76.00,0.00,13.00,0.00,0.00,20.00,15.00,20.00,0.00,0.00,0.00,0.00,0.00,12.00,11.00,0.00,0.00,0.00,0.00,0.22,0.00,0.21,0.12,0.00,0.00,0.00,0.00,0.00,0.00,0.26,0.17,0.65,0.21,0.81,0.93,0.36,0.00,0.00,0.57,0.00,2.46
max,119.00,172.00,"4,186.00","5,586.00","93,033.00","13,551,821.17","10,125,176.68","7,895,857.12","8,065,348.67",103.00,100.00,571.00,"3,970.00","48,831.00","716,880.80","373,470.66","290,966.90","293,406.58",58.00,69.00,"4,180.00","5,566.00","17,871.00","13,543,621.05","10,118,051.82","7,890,551.74","8,060,083.23",15.00,6.00,31.00,186.00,"82,210.00","80,780.80","33,201.16","26,191.81","25,668.00",91.00,558.00,"2,048.00","1,824.00",104.00,"2,586.00","1,600.00","3,530.00",769.00,114.00,309.00,27.00,110.00,"3,300.00","1,206.00",0.01,0.49,0.42,0.83,0.87,0.35,0.85,0.85,0.14,0.02,0.35,0.42,0.44,0.48,0.73,0.75,1.00,0.69,1.00,1.00,0.79,0.66,0.12,1.00,0.50,5.62

Fraudulent providers tend to submit claims for services with higher allowed amounts and receive higher payments compared to the general population of providers. Also, their beneficiary risk scores tend to be higher as well.

In [24]:
# how many years does each fraudulant provider appear in the dataset?
yrs_fraud = df_fraud[['npi','Year']].groupby('npi').nunique()
yrs_fraud = yrs_fraud.drop('npi',axis=1).sort_values(by='Year',ascending=False).reset_index()
yrs_fraud = yrs_fraud.groupby('Year').nunique()
yrs_fraud.drop('Year',axis=1)

      npi
Year
1      57
2      47
3      34

In [25]:
df_rejoin = pd.merge(labs, df, how='right', on='npi')
df_rejoin_fraud = df_rejoin[df_rejoin.fraud_flag.isna()==False]
df_rejoin_fraud.head()

,npi,fraud_flag,EXCLDATE,Rfrg_Prvdr_Last_Name_Org,Rfrg_Prvdr_First_Name,Rfrg_Prvdr_MI,Rfrg_Prvdr_Crdntls,Rfrg_Prvdr_Ent_Cd,Rfrg_Prvdr_St1,Rfrg_Prvdr_St2,Rfrg_Prvdr_City,Rfrg_Prvdr_State_Abrvtn,Rfrg_Prvdr_State_FIPS,Rfrg_Prvdr_Zip5,Rfrg_Prvdr_RUCA,Rfrg_Prvdr_RUCA_Desc,Rfrg_Prvdr_Cntry,Rfrg_Prvdr_Spclty_Desc,Rfrg_Prvdr_Spclty_Srce,Tot_Suplrs,Tot_Suplr_HCPCS_Cds,Tot_Suplr_Benes,Tot_Suplr_Clms,Tot_Suplr_Srvcs,Suplr_Sbmtd_Chrgs,Suplr_Mdcr_Alowd_Amt,Suplr_Mdcr_Pymt_Amt,Suplr_Mdcr_Stdzd_Pymt_Amt,DME_Sprsn_Ind,DME_Tot_Suplrs,DME_Tot_Suplr_HCPCS_Cds,DME_Tot_Suplr_Benes,DME_Tot_Suplr_Clms,DME_Tot_Suplr_Srvcs,DME_Suplr_Sbmtd_Chrgs,DME_Suplr_Mdcr_Alowd_Amt,DME_Suplr_Mdcr_Pymt_Amt,DME_Suplr_Mdcr_Stdzd_Pymt_Amt,POS_Sprsn_Ind,POS_Tot_Suplrs,POS_Tot_Suplr_HCPCS_Cds,POS_Tot_Suplr_Benes,POS_Tot_Suplr_Clms,POS_Tot_Suplr_Srvcs,POS_Suplr_Sbmtd_Chrgs,POS_Suplr_Mdcr_Alowd_Amt,POS_Suplr_Mdcr_Pymt_Amt,POS_Suplr_Mdcr_Stdzd_Pymt_Amt,Drug_Sprsn_Ind,Drug_Tot_Suplrs,Drug_Tot_Suplr_HCPCS_Cds,Drug_Tot_Suplr_Benes,Drug_Tot_Suplr_Clms,Drug_Tot_Suplr_Srvcs,Drug_Suplr_Sbmtd_Chrgs,Drug_Suplr_Mdcr_Alowd_Amt,Drug_Suplr_Mdcr_Pymt_Amt,Drug_Suplr_Mdcr_Stdzd_Pymt_Amt,Bene_Avg_Age,Bene_Age_LT_65_Cnt,Bene_Age_65_74_Cnt,Bene_Age_75_84_Cnt,Bene_Age_GT_84_Cnt,Bene_Feml_Cnt,Bene_Male_Cnt,Bene_Race_Wht_Cnt,Bene_Race_Black_Cnt,Bene_Race_Api_Cnt,Bene_Race_Hspnc_Cnt,Bene_Race_Natind_Cnt,Bene_Race_Othr_Cnt,Bene_Ndual_Cnt,Bene_Dual_Cnt,Bene_CC_BH_ADHD_OthCD_V1_Pct,Bene_CC_BH_Alcohol_Drug_V1_Pct,Bene_CC_BH_Tobacco_V1_Pct,Bene_CC_BH_Alz_NonAlzdem_V2_Pct,Bene_CC_BH_Anxiety_V1_Pct,Bene_CC_BH_Bipolar_V1_Pct,Bene_CC_BH_Mood_V2_Pct,Bene_CC_BH_Depress_V1_Pct,Bene_CC_BH_PD_V1_Pct,Bene_CC_BH_PTSD_V1_Pct,Bene_CC_BH_Schizo_OthPsy_V1_Pct,Bene_CC_PH_Asthma_V2_Pct,Bene_CC_PH_Afib_V2_Pct,Bene_CC_PH_Cancer6_V2_Pct,Bene_CC_PH_CKD_V2_Pct,Bene_CC_PH_COPD_V2_Pct,Bene_CC_PH_Diabetes_V2_Pct,Bene_CC_PH_HF_NonIHD_V2_Pct,Bene_CC_PH_Hyperlipidemia_V2_Pct,Bene_CC_PH_Hypertension_V2_Pct,Bene_CC_PH_IschemicHeart_V2_Pct,Bene_CC_PH_Osteoporosis_V2_Pct,Bene_CC_PH_Parkinson_V2_Pct,Bene_CC_PH_Arthritis_V2_Pct,Bene_CC_PH_Stroke_TIA_V2_Pct,Bene_Avg_Risk_Scre,Year,target
0,1972596757,1.00,"2,023.00",Naushad,Abdul,N,md,I,2865 James Blvd,NaN,Poplar Bluff,MO,29,63901,4.00,Micropolitan area core: primary flow within an...,US,Pain Management,Claim-Specialty,6,14,5.00,22,27,"13,371.30","10,217.71","7,784.70","7,384.51",NaN,2.00,3.00,5.00,11.00,12.00,"1,380.61",862.55,658.97,436.15,NaN,6.00,11.00,0.00,11.00,15.00,"11,990.69","9,355.16","7,125.73","6,948.36",NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,64.12,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.26,2021,1
1,1265697478,1.00,"2,024.00",Balger,Abigail,NaN,md,I,805 E Geneva Dr,NaN,Dewitt,MI,26,48820,1.00,Metropolitan area core: primary flow within an...,US,Emergency Medicine,NPPES-Specialty,1,8,34.00,34,99,"75,655.00","53,841.66","40,491.75","38,453.43",NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,1.00,8.00,34.00,34.00,99.00,"75,655.00","53,841.66","40,491.75","38,453.43",NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,68.35,0.00,16.00,13.00,0.00,20.00,14.00,32.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.44,0.00,0.41,0.32,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.41,0.00,0.74,0.79,0.00,0.00,0.00,0.53,0.00,1.43,2021,1
2,1922096221,1.00,"2,024.00",Alperovich,Alexander,NaN,md,I,1340 Union University Dr,NaN,Jackson,TN,47,38305,1.00,Metropolitan area core: primary flow within an...,US,Cardiology,Claim-Specialty,9,24,33.00,137,318,"171,131.05","78,376.77","62,002.29","59,621.86",NaN,9.00,24.00,33.00,137.00,318.00,"171,131.05","78,376.77","62,002.29","59,621.86",NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,76.64,0.00,12.00,14.00,0.00,16.00,17.00,32.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.33,0.00,0.33,0.00,0.00,0.00,0.00,0.00,0.39,0.00,0.36,0.39,0.55,0.67,0.88,0.97,0.73,0.00,0.00,0.67,0.00,1.86,2021,1
3,1922096221,1.00,"2,024.00",Alperovich,Alexander,NaN,md,I,1340 Union University Dr,NaN,Jackson,TN,47,38305,1.00,Metropolitan area core: primary flow within an...,US,Cardiology,Claim-Specialty,6,18,23.00,112,271,"131,316.48","62,248.82","48,394.75","47,474.88",NaN,6.00,18.00,23.00,112.00,271.00,"131,316.48","62,248.82","48,394.75","47,474.88",NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,76.04,0.00,0.00,0.00,0.00,0.00,0.00,22.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.48,0.61,0.91,1.00,0.74,0.00,0.00,0.70,0.00,1.66,2022,1
4,1922096221,1.00,"2,024.00",Alperovich,Alexander,NaN,md,I,1340 Union University Dr,NaN,Jackson,TN,47,38305,1.00,Metropolitan area core: primary flow within an...,US,Cardiology,Claim-Specialty,4,17,18.00,105,297,"117,715.10","51,888.83","40,041.23","39,467.17",NaN,4.00,17.00,18.00,105.00,297.00,"117,715.10","51,888.83","40,041.23","39,467.17",NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,75.72,0.00,0.00,12.00,0.00,0.00,0.00,17.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.94,1.00,0.61,0.00,0.00,0.00,0.00,1.77,2023,1

In [26]:
df_rejoin_fraud[df_rejoin_fraud.EXCLDATE <= df_rejoin_fraud.Year] # change from <= to < to check for claims after excl

,npi,fraud_flag,EXCLDATE,Rfrg_Prvdr_Last_Name_Org,Rfrg_Prvdr_First_Name,Rfrg_Prvdr_MI,Rfrg_Prvdr_Crdntls,Rfrg_Prvdr_Ent_Cd,Rfrg_Prvdr_St1,Rfrg_Prvdr_St2,Rfrg_Prvdr_City,Rfrg_Prvdr_State_Abrvtn,Rfrg_Prvdr_State_FIPS,Rfrg_Prvdr_Zip5,Rfrg_Prvdr_RUCA,Rfrg_Prvdr_RUCA_Desc,Rfrg_Prvdr_Cntry,Rfrg_Prvdr_Spclty_Desc,Rfrg_Prvdr_Spclty_Srce,Tot_Suplrs,Tot_Suplr_HCPCS_Cds,Tot_Suplr_Benes,Tot_Suplr_Clms,Tot_Suplr_Srvcs,Suplr_Sbmtd_Chrgs,Suplr_Mdcr_Alowd_Amt,Suplr_Mdcr_Pymt_Amt,Suplr_Mdcr_Stdzd_Pymt_Amt,DME_Sprsn_Ind,DME_Tot_Suplrs,DME_Tot_Suplr_HCPCS_Cds,DME_Tot_Suplr_Benes,DME_Tot_Suplr_Clms,DME_Tot_Suplr_Srvcs,DME_Suplr_Sbmtd_Chrgs,DME_Suplr_Mdcr_Alowd_Amt,DME_Suplr_Mdcr_Pymt_Amt,DME_Suplr_Mdcr_Stdzd_Pymt_Amt,POS_Sprsn_Ind,POS_Tot_Suplrs,POS_Tot_Suplr_HCPCS_Cds,POS_Tot_Suplr_Benes,POS_Tot_Suplr_Clms,POS_Tot_Suplr_Srvcs,POS_Suplr_Sbmtd_Chrgs,POS_Suplr_Mdcr_Alowd_Amt,POS_Suplr_Mdcr_Pymt_Amt,POS_Suplr_Mdcr_Stdzd_Pymt_Amt,Drug_Sprsn_Ind,Drug_Tot_Suplrs,Drug_Tot_Suplr_HCPCS_Cds,Drug_Tot_Suplr_Benes,Drug_Tot_Suplr_Clms,Drug_Tot_Suplr_Srvcs,Drug_Suplr_Sbmtd_Chrgs,Drug_Suplr_Mdcr_Alowd_Amt,Drug_Suplr_Mdcr_Pymt_Amt,Drug_Suplr_Mdcr_Stdzd_Pymt_Amt,Bene_Avg_Age,Bene_Age_LT_65_Cnt,Bene_Age_65_74_Cnt,Bene_Age_75_84_Cnt,Bene_Age_GT_84_Cnt,Bene_Feml_Cnt,Bene_Male_Cnt,Bene_Race_Wht_Cnt,Bene_Race_Black_Cnt,Bene_Race_Api_Cnt,Bene_Race_Hspnc_Cnt,Bene_Race_Natind_Cnt,Bene_Race_Othr_Cnt,Bene_Ndual_Cnt,Bene_Dual_Cnt,Bene_CC_BH_ADHD_OthCD_V1_Pct,Bene_CC_BH_Alcohol_Drug_V1_Pct,Bene_CC_BH_Tobacco_V1_Pct,Bene_CC_BH_Alz_NonAlzdem_V2_Pct,Bene_CC_BH_Anxiety_V1_Pct,Bene_CC_BH_Bipolar_V1_Pct,Bene_CC_BH_Mood_V2_Pct,Bene_CC_BH_Depress_V1_Pct,Bene_CC_BH_PD_V1_Pct,Bene_CC_BH_PTSD_V1_Pct,Bene_CC_BH_Schizo_OthPsy_V1_Pct,Bene_CC_PH_Asthma_V2_Pct,Bene_CC_PH_Afib_V2_Pct,Bene_CC_PH_Cancer6_V2_Pct,Bene_CC_PH_CKD_V2_Pct,Bene_CC_PH_COPD_V2_Pct,Bene_CC_PH_Diabetes_V2_Pct,Bene_CC_PH_HF_NonIHD_V2_Pct,Bene_CC_PH_Hyperlipidemia_V2_Pct,Bene_CC_PH_Hypertension_V2_Pct,Bene_CC_PH_IschemicHeart_V2_Pct,Bene_CC_PH_Osteoporosis_V2_Pct,Bene_CC_PH_Parkinson_V2_Pct,Bene_CC_PH_Arthritis_V2_Pct,Bene_CC_PH_Stroke_TIA_V2_Pct,Bene_Avg_Risk_Scre,Year,target
16,1760425458,1.00,"2,023.00",Brutus,Andre,NaN,NaN,I,650 Fulton Street,Brooklyn Plaza Medical Center,Brooklyn,NY,36,11217,1.00,Metropolitan area core: primary flow within an...,US,Internal Medicine,Claim-Specialty,5,8,5.00,16,1024,"3,587.54","1,689.78","1,259.85","1,337.13",NaN,4.00,5.00,5.00,15.00,22.00,"1,727.54",573.46,390.72,390.72,*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,68.80,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.16,2023,0
26,1629179312,1.00,"2,022.00",Kidd,Avian,D,md,I,2900 Mckinnon St # 502,NaN,Dallas,TX,48,75201,1.00,Metropolitan area core: primary flow within an...,US,Internal Medicine,NPPES-Specialty,13,63,24.00,108,9659,"146,437.68","44,600.88","35,066.77","35,166.13",NaN,9.00,35.00,19.00,85.00,"1,514.00","30,844.32","21,382.28","16,503.89","17,202.56",*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,#,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,73.25,0.00,0.00,0.00,0.00,13.00,11.00,0.00,14.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.54,0.67,0.00,0.88,0.88,0.00,0.00,0.00,0.00,0.00,0.00,0.58,0.00,0.67,0.50,0.71,0.96,0.00,0.00,0.00,0.46,0.46,5.36,2022,0
31,1326209354,1.00,"2,021.00",Iguh,Bernadette,U,md,I,12660 Beechnut St,Suite 110,Houston,TX,48,77072,1.00,Metropolitan area core: primary flow within an...,US,Family Practice,NPPES-Specialty,5,19,5.00,25,6603,"87,732.02","5,620.81","4,323.56","4,723.97",NaN,4.00,9.00,5.00,15.00,437.00,"2,567.99",608.56,486.81,537.91,*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,#,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,47.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.06,2021,0
34,1417068511,1.00,"2,023.00",Bhandari,Bhupinder,N,md,I,3755 Beacon Ave,NaN,Fremont,CA,06,94538,1.00,Metropolitan area core: primary flow within an...,US,Internal Medicine,NPPES-Taxonomy,10,4,5.00,11,320,"1,750.34",204.35,160.19,160.19,NaN,10.00,3.00,5.00,11.00,22.00,"1,651.75",193.92,152.02,152.02,#,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,78.50,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.33,2023,0
39,1942287735,1.00,"2,022.00",Dickinson,Brett,NaN,md,I,515 Maple Valley Dr,NaN,Farmington,MO,29,63640,4.00,Micropolitan area core: primary flow within an...,US,Family Practice,NPPES-Specialty,25,28,38.00,139,3536,"58,078.07","22,319.85","15,917.11","13,472.07",NaN,20.00,20.00,33.00,129.00,347.00,"43,220.57","16,598.99","11,746.08","9,515.46",*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,73.26,0.00,15.00,14.00,0.00,20.00,18.00,36.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.34,0.00,0.34,0.34,0.00,0.00,0.00,0.00,0.39,0.32,0.32,0.34,0.66,0.29,0.82,0.89,0.45,0.00,0.00,0.45,0.00,1.75,2022,0
61,1033280003,1.00,"2,022.00",House,David,D,md,I,441 N Lakeview Ave,NaN,Anaheim,CA,06,92807,1.00,Metropolitan area core: primary flow within an...,US,Family Practice,NPPES-Specialty,11,19,23.00,28,236,"10,964.79","2,889.10","1,224.05","1,034.83",NaN,11.00,18.00,23.00,28.00,161.00,"10,952.04","2,885.65","1,221.29","1,032.13",#,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,68.22,0.00,13.00,0.00,0.00,0.00,0.00,20.00,0.00,0.00,0.00,0.00,0.00,12.00,11.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.70,0.00,0.70,0.87,0.00,0.00,0.00,0.00,0.00,1.92,2022,0
77,1376854968,1.00,"2,022.00",Canova,Eduardo,C,md,I,801 N Us Highway 83,NaN,Zapata,TX,48,78076,4.00,Micropolitan area core: primary flow within an...,US,Internal Medicine,Claim-Specialty,24,31,36.00,116,4698,"24,601.88","8,467.52","6,156.61","6,216.72",NaN,22.00,24.00,35.00,111.00,787.00,"15,094.21","6,628.67","4,804.21","4,852.20",*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,74.44,0.00,13.00,13.00,0.00,21.00,15.00,0.00,0.00,0.00,35.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.31,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.50,0.00,0.92,0.31,1.00,1.00,0.53,0.00,0.00,0.61,0.00,3.92,2022,0
98,1083654669,1.00,"2,023.00",Samuels,Garfield,H,md,I,4452 Corporation Ln,Ste 300,Virginia Beach,VA,51,23462,1.00,Metropolitan area core: primary flow within an...,US,Internal Medicine,NPPES-Specialty,9,25,12.00,51,3253,"28,869.60","8,357.64","5,696.45","6,960.67",NaN,8.00,20.00,11.00,43.00,296.00,"21,974.66","5,844.13","3,735.28","4,470.57",*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,#,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,70.92,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.92,0.00,0.00,0.00,0.00,0.00,2.66,2023,0
99,1073792172,1.00,"2,021.00",Myint,Gerald,H,md,I,27206 Calaroga Ave,Suite 205,Hayward,CA,06,94545,1.00,Metropolitan area core: primary flow within an...,US,Internal Medicine,Claim-Specialty,21,39,35.00,90,5381,"49,032.90","17,667.97","12,755.35","12,596.34",NaN,18.00,20.00,33.00,83.00,"1,788.00","9,140.55","3,041.36","1,594.38","1,702.03",*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,74.37,0.00,12.00,0.00,0.00,15.00,20.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.46,0.37,0.00,0.00,0.00,0.00,0.00,0.00,0.40,0.34,0.77,0.60,0.77,0.97,0.63,0.00,0.00,0.40,0.00,2.70,2021,0
111,1700813607,1.00,"2,023.00",Ali,Iftikhar,NaN,md,I,2705 S Range Line Rd Ste A,NaN,Joplin,MO,29,64804,1.00,Metropolitan area core: primary flow within an...,US,Internal Medicine,NPPES-Specialty,6,9,5.00,30,533,"48,094.26","15,829.37","11,199.67","11,144.94",NaN,5.00,6.00,5.00,28.00,28.00,"45,068.26","14,455.90","11,052.67","10,997.94",#,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,73.12,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.77,2023,0
112,1922280254,1.00,"2,021.00",Mayhew,Jami,L,np,I,393 E Edwardsville Rd,NaN,Wood River,IL,17,62095,1.10,Secondary flow 30% to <50% to a larger urbaniz...,US,Nurse Practitioner,NPPES-Specialty,6,8,5.00,30,270,"7,108.15","1,932.12","1,176.92","1,320.58",NaN,5.00,7.00,5.00,28.00,30.00,"6,064.15","1,425.72",934.20,"1,082.71",*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,#,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,77.38,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.53,2021,0
119,1821123803,1.00,"2,021.00",Runyan,Jason,NaN,np,I,13927 Shipwreck Cir N,NaN,Jacksonville,FL,12,32224,1.00,Metropolitan area core: primary flow within an...,US,Nurse Practitioner,NPPES-Specialty,9,18,5.00,17,126,"16,995.18","5,381.71","4,127.51","4,179.13",NaN,9.00,18.00,5.00,17.00,126.00,"16,995.18","5,381.71","4,127.51","4,179.13",NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,73.30,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3.72,2021,0
122,1093988008,1.00,"2,023.00",Shires,Jay,G,md,I,294 Summar Dr,NaN,Jackson,TN,47,38301,1.00,Metropolitan area core: primary flow within an...,US,Family Practice,NPPES-Specialty,5,12,34.00,137,5096,"50,413.82","26,501.20","19,394.08","18,125.39",NaN,5.00,8.00,32.00,119.00,154.00,"32,000.16","20,267.92","14,507.18","13,848.04",NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,76.32,0.00,13.00,0.00,0.00,21.00,13.00,29.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.62,0.00,0.62,0.59,0.00,0.00,0.00,0.00,0.47,0.00,0.00,0.41,0.50,0.47,0.91,1.00,0.56,0.00,0.00,0.62,0.00,3.23,2023,0
124,1841287679,1.00,"2,022.00",Hoffman,Jeffrey,D,md,I,101 Cabarrus Ave E,NaN,Concord,NC,37,28025,1.00,Metropolitan area core: primary flow within an...,US,Family Practice,NPPES-Specialty,5,16,5.00,24,1434,"10,694.76","4,070.32","2,989.92","3,485.37",NaN,4.00,15.00,5.00,21.00,84.00,"5,294.76","1,518.82","1,155.53","1,318.39",*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,#,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,67.40,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.54,2022,0
130,1558407411,1.00,"2,023.00",Aronowitz,Joel,A,md,I,414 N Camden Dr Ste 1010,NaN,Beverly Hills,CA,06,90210,1.00,Metropolitan area core: primary flow within an...,US,Plastic and Reconstructive Surgery,Claim-Specialty,3,14,5.00,16,3929,"10,040.96","7,696.07","5,890.63","6,098.61",NaN,3.00,14.00,5.00,16.00,"3,929.00","10,040.96","7,696.07","5,890.63","6,098.61",NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,73.78,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,5.37,2023,0
159,1144242090,1.00,"2,023.00",Anukwu,Linus,U,md,I,4500 Memorial Dr,NaN,Belleville,IL,17,62226,1.00,Metropolitan area core: primary flow within an...,US,Family Practice,NPPES-Specialty,2,5,5.00,11,1288,"1,316.56",311.19,205.64,204.58,NaN,2.00,4.00,5.00,11.00,13.00,"1,099.81",268.65,178.46,177.40,#,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,68.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.86,2023,0
175,1649348343,1.00,"2,023.00",Massullo,Mary-Helene,A,do,I,501 Van Buren St,Suite 206,Fostoria,OH,39,44830,4.00,Micropolitan area core: primary flow within an...,US,General Surgery,NPPES-Specialty,1,1,11.00,86,86,"27,950.00","25,517.92","19,905.20","19,905.20",NaN,1.00,1.00,11.00,86.00,86.00,"27,950.00","25,517.92","19,905.20","19,905.20",NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,76.73,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.84,2023,0
191,1982743589,1.00,"2,022.00",Leiva,Orlando,E,md,I,6230 Sw 70th St,NaN,South Miami,FL,12,33143,1.00,Metropolitan area core: primary flow within an...,US,General Practice,Claim-Specialty,3,7,5.00,13,274,"8,832.76","7,382.76","5,789.89","5,816.51",NaN,3.00,7.00,5.00,13.00,274.00,"8,832.76","7,382.76","5,789.89","5,816.51",NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,72.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.86,2022,0
206,1982693511,1.00,"2,023.00",Costa,Richard,C,do,I,339 N Route 73,Suite 1,Berlin,NJ,34,08009,1.00,Metropolitan area core: primary flow within an...,US,Family Practice,NPPES-Specialty,13,35,12.00,54,784,"16,126.72","6,730.07","4,947.84","5,451.60",NaN,8.00,25.00,5.00,43.00,102.00,"10,886.43","3,425.05","2,627.35","3,081.81",#,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,76.25,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.92,0.92,0.00,0.00,0.00,0.00,0.00,1.29,2023,0
209,1992735591,1.00,"2,023.00",Kroop,Richard,J,md,I,201 S Buena Vista St,Suite # 300,Burbank,CA,06,91505,1.00,Metropolitan area core: primary flow within an...,US,Internal Medicine,NPPES-Specialty,10,6,13.00,15,345,"2,960.36",454.80,283.31,279.91,NaN,10.00,5.00,13.00,15.00,45.00,"2,800.64",444.30,283.31,279.91,#,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,77.69,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.92,0.00,0.92,1.00,0.00,0.00,0.00,0.00,0.00,2.80,2023,0
225,1336220276,1.00,"2,023.00",Nelson,Scott,NaN,md,I,907 E Sunflower Rd,Ste 101,Cleveland,MS,28,38732,4.00,Micropolitan area core: primary flow within an...,US,Family Practice,Claim-Specialty,4,6,5.00,30,486,"9,890.78","3,098.82","2,277.49","1,859.41",NaN,4.00,5.00,5.00,30.00,38.00,"9,705.00","3,085.16","2,266.78","1,848.70",#,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,73.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.28,2023,0
239,1356530380,1.00,"2,023.00",Arnold,Steven,J,md,I,11525 Taylor Wells Rd,NaN,Chardon,OH,39,44024,2.00,Metropolitan area high commuting: primary flow...,US,Family Practice,Claim-Specialty,5,20,5.00,42,8166,"18,250.87","10,819.80","8,482.71","7,971.50",*,3.00,6.00,5.00,19.00,43.00,"6,075.05","1,947.45","1,449.27","1,540.02",NaN,2.00,4.00,0.00,15.00,542.00,"3,971.41","3,185.88","2,497.76","2,713.43",#,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,55.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.39,2023,0
244,1194803627,1.00,"2,023.00",Rosan,Stuart,W,do,I,620 Easton Rd,Suite 7,Warrington,PA,42,18976,1.00,Metropolitan area core: primary flow within an...,US,Family Practice,NPPES-Specialty,5,10,5.00,23,3753,"9,321.06","2,648.80","1,886.36","2,456.43",NaN,3.00,6.00,5.00,11.00,16.00,"2,868.56",563.09,428.38,619.18,*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,*,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,59.60,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,4.52,2023,0
261,1184623514,1.00,"2,022.00",Malviya,Vinay,K,md,I,29877 Telegraph Rd Ste 304,NaN,Southfield,MI,26,48034,1.00,Metropolitan area core: primary flow within an...,US,Obstetrics & Gynecology,NPPES-Taxonomy,5,13,5.00,16,1526,"11,930.94","5,261.04","3,966.18","3,932.03",*,3.00,6.00,5.00,19.00,43.00,"6,075.05","1,947.45","1,449.27","1,540.02",NaN,5.00,12.00,0.00,14.00,"1,301.00","11,798.19","5,195.79","3,914.15","3,880.88",#,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,79.29,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.91,2022,0
264,1447286158,1.00,"2,023.00",Aboughali,Wael,A,md,I,1602 Garth Rd,NaN,Baytown,TX,48,77520,1.00,Metropolitan area core: primary flow within an...,US,Family Practice,NPPES-Specialty,3,11,5.00,11,217,"2,185.70",612.62,233.96,380.95,*,3.00,6.00,5.00,19.00,43.00,"6,075.05","1,947.45","1,449.27","1,540.02",#,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,57.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.48,2023,0
278,1467554071,1.00,"2,023.00",Zhang,Zheng-Gang,NaN,md,I,25 N 14th St,Suite 920,San Jose,CA,06,95112,1.00,Metropolitan area core: primary flow within an...,US,Internal Medicine,NPPES-Specialty,2,7,5.00,12,1465,"5,748.01","2,042.65","1,138.47","1,733.42",NaN,2.00,5.00,5.00,11.00,13.00,"4,214.53",509.17,113.41,302.67,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,81.25,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,4.78,2023,0

Some providers had claims the year they were added to the exclusion list for fraud. However, no providers have claims for a year after they were added to the exclusion list for fraud.