## Provider_Amount_Metrics
Purpose of this notebook is to derive a dataset that contains NPI-level aggregated statistics (mean, sum, median, standard deviation, min, and max) for all amount-related metrics, along with an exclusion flag indicating which NPIs are excluded.

End Result:

Saved the cleaned dataset to a shared team directory: /dsa/groups/casestudycf25/team02/DMEPOS_Amount_stats.csv

In [5]:
# Loading the required Libraries and Dataset
from pathlib import Path
import pandas as pd
df=pd.read_csv("/dsa/groups/casestudycf25/team02/DMEPOS_RefPro_Ser_nar_clean.csv")

C:\Users\kamat\AppData\Local\Temp\ipykernel_13712\2095555133.py:4: DtypeWarning: Columns (11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r"D:\DATA\Project\Current focus\DMEPOS - By Referral Provider and Service\DMEPOS_RefPro_Ser_nar_clean.csv")

In [6]:
# Loading the LEIE exclusion list
d = pd.read_csv("/dsa/groups/casestudycf25/team02/leie_with_valid_npi_clean.csv",dtype={"Suplr_Prvdr_RUCA": "float64"}, na_values=["NA"])

In [7]:
#Attribute Names

df.columns

Index(['Year', 'Rfrg_NPI', 'Rfrg_Prvdr_Last_Name_Org', 'Rfrg_Prvdr_First_Name',
       'Rfrg_Prvdr_MI', 'Rfrg_Prvdr_Crdntls', 'Rfrg_Prvdr_Ent_Cd',
       'Rfrg_Prvdr_St1', 'Rfrg_Prvdr_St2', 'Rfrg_Prvdr_City',
       'Rfrg_Prvdr_State_Abrvtn', 'Rfrg_Prvdr_State_FIPS', 'Rfrg_Prvdr_Zip5',
       'Rfrg_Prvdr_RUCA_Cat', 'Rfrg_Prvdr_RUCA', 'Rfrg_Prvdr_RUCA_Desc',
       'Rfrg_Prvdr_Cntry', 'Rfrg_Prvdr_Spclty_Cd', 'Rfrg_Prvdr_Spclty_Desc',
       'Rfrg_Prvdr_Spclty_Srce', 'RBCS_Lvl', 'RBCS_Id', 'RBCS_Desc',
       'HCPCS_CD', 'HCPCS_Desc', 'Suplr_Rentl_Ind', 'Tot_Suplrs',
       'DME_Sprsn_Ind', 'Tot_Suplr_Benes', 'Tot_Suplr_Clms', 'Tot_Suplr_Srvcs',
       'Avg_Suplr_Sbmtd_Chrg', 'Avg_Suplr_Mdcr_Alowd_Amt',
       'Avg_Suplr_Mdcr_Pymt_Amt', 'Avg_Suplr_Mdcr_Stdzd_Amt', 'Excluded',
       'Supplier'],
      dtype='object')

In [8]:
# Selecting only Amount based variables
amt = ['Rfrg_NPI','Avg_Suplr_Sbmtd_Chrg', 'Avg_Suplr_Mdcr_Alowd_Amt','Avg_Suplr_Mdcr_Pymt_Amt', 'Avg_Suplr_Mdcr_Stdzd_Amt']
df1 = df[amt]
df1

,Rfrg_NPI,Avg_Suplr_Sbmtd_Chrg,Avg_Suplr_Mdcr_Alowd_Amt,Avg_Suplr_Mdcr_Pymt_Amt,Avg_Suplr_Mdcr_Stdzd_Amt
0,1003000126,46.336250,20.097500,14.857500,15.280000
1,1003000126,360.770000,98.223158,72.843684,79.753158
2,1003000126,92.000000,39.230000,31.385455,33.552727
3,1003000126,20.000000,10.210909,8.169091,8.456364
4,1003000480,272.003846,80.513846,64.407692,84.701538
...,...,...,...,...,...
4413113,1992999551,54.000667,21.794667,17.090000,21.330000
4413114,1992999551,9.804189,2.351892,1.768649,2.527568
4413115,1992999551,126.206970,34.797273,27.280909,41.530000
4413116,1992999551,362.000000,85.000000,61.086667,93.711667
4413117,1992999551,125.000000,43.150000,31.010833,33.349167

In [9]:
#Attribute Names

df1.columns

Index(['Rfrg_NPI', 'Avg_Suplr_Sbmtd_Chrg', 'Avg_Suplr_Mdcr_Alowd_Amt',
       'Avg_Suplr_Mdcr_Pymt_Amt', 'Avg_Suplr_Mdcr_Stdzd_Amt'],
      dtype='object')

In [10]:
# Grouping by NPI and computing mean, sum, median, std, min, max
cols_to_agg = ['Avg_Suplr_Sbmtd_Chrg','Avg_Suplr_Mdcr_Alowd_Amt','Avg_Suplr_Mdcr_Pymt_Amt','Avg_Suplr_Mdcr_Stdzd_Amt']

npi_stats = df1.groupby('Rfrg_NPI')[cols_to_agg].agg(['mean', 'sum', 'median', 'std', 'min', 'max'])

npi_stats

           Avg_Suplr_Sbmtd_Chrg                                       \
                           mean          sum      median         std
Rfrg_NPI
1003000126           154.965761  1394.691851   85.053333  147.551365
1003000480           272.003846   272.003846  272.003846         NaN
1003000522           133.101129   266.202258  133.101129  122.893562
1003000530           165.245147  1321.961175   52.694357  190.652061
1003000597            11.385487    68.312921    8.053952    9.950240
...                         ...          ...         ...         ...
1992998736             8.490732     8.490732    8.490732         NaN
1992999031           133.678036   267.356071  133.678036   23.082743
1992999122           120.718665  4587.309264   50.959459  153.072464
1992999551           149.305598  3434.028746   91.072000  174.972748
1992999874           175.000000   175.000000  175.000000         NaN

                                   Avg_Suplr_Mdcr_Alowd_Amt               \
                   min         max                     mean          sum
Rfrg_NPI
1003000126   20.000000  369.804068                47.053762   423.483862
1003000480  272.003846  272.003846                80.513846    80.513846
1003000522   46.202258  220.000000                22.805968    45.611935
1003000530    8.582462  408.106667                35.321549   282.572391
1003000597    0.390000   25.536875                 5.845194    35.071166
...                ...         ...                      ...          ...
1992998736    8.490732    8.490732                 2.360000     2.360000
1992999031  117.356071  150.000000                 8.448323    16.896645
1992999122    0.208718  519.510000                39.271244  1492.307280
1992999551    9.804189  760.480000                42.163187   969.753293
1992999874  175.000000  175.000000                51.310769    51.310769

                                  ... Avg_Suplr_Mdcr_Pymt_Amt             \
               median        std  ...                  median        std
Rfrg_NPI                          ...
1003000126  21.348889  38.863058  ...               14.857500  28.362857
1003000480  80.513846        NaN  ...               64.407692        NaN
1003000522  22.805968  20.030967  ...               18.243952  16.024522
1003000530   8.476311  41.668802  ...                6.253973  30.757069
1003000597   4.867170   4.982492  ...                3.734386   3.520405
...               ...        ...  ...                     ...        ...
1992998736   2.360000        NaN  ...                1.850000        NaN
1992999031   8.448323  10.679685  ...                5.432927   6.926792
1992999122   8.380496  68.936965  ...                6.302793  53.656704
1992999551  34.797273  52.425067  ...               27.280909  39.204298
1992999874  51.310769        NaN  ...               41.045385        NaN

                                  Avg_Suplr_Mdcr_Stdzd_Amt               \
                  min         max                     mean          sum
Rfrg_NPI
1003000126   8.169091   72.843684                40.955161   368.596445
1003000480  64.407692   64.407692                84.701538    84.701538
1003000522   6.912903   29.575000                19.471129    38.942258
1003000530   1.056667   67.595000                34.795433   278.363463
1003000597   0.112054    8.331875                 4.670143    28.020858
...               ...         ...                      ...          ...
1992998736   1.850000    1.850000                 2.595000     2.595000
1992999031   0.534946   10.330909                 5.396201    10.792403
1992999122   0.018742  209.144127                31.125937  1182.785602
1992999551   1.463636  189.789091                38.425962   883.797133
1992999874  41.045385   41.045385                53.839231    53.839231


               median        std        min         max
Rfrg_NPI
1003000126  19.462308  34.424652   8.456364   89.597353
1003000480  84.701538        NaN  84.701538   84.701538
1003000522  19.471129  18.199332   6.602258   32.340000
1003000530   6.125764  42.309591   1.024167   90.520000
1003000597   4.210925   3.984015   0.112054    9.864062
...               ...        ...        ...         ...
1992998736   2.595000        NaN   2.595000    2.595000
1992999031   5.396201   6.878450   0.532403   10.260000
1992999122   6.368296  54.252385   0.018371  209.144127
1992999551  32.449091  42.058405   2.103617  189.789091
1992999874  53.839231        NaN  53.839231   53.839231

[398034 rows x 24 columns]

In [12]:
# Flattening the multindex to make it look pretty
npi_stats.columns = ['_'.join(col).strip() for col in npi_stats.columns.values]
npi_stats = npi_stats.reset_index()
npi_stats.head()

,Rfrg_NPI,Avg_Suplr_Sbmtd_Chrg_mean,Avg_Suplr_Sbmtd_Chrg_sum,Avg_Suplr_Sbmtd_Chrg_median,Avg_Suplr_Sbmtd_Chrg_std,Avg_Suplr_Sbmtd_Chrg_min,Avg_Suplr_Sbmtd_Chrg_max,Avg_Suplr_Mdcr_Alowd_Amt_mean,Avg_Suplr_Mdcr_Alowd_Amt_sum,Avg_Suplr_Mdcr_Alowd_Amt_median,...,Avg_Suplr_Mdcr_Pymt_Amt_median,Avg_Suplr_Mdcr_Pymt_Amt_std,Avg_Suplr_Mdcr_Pymt_Amt_min,Avg_Suplr_Mdcr_Pymt_Amt_max,Avg_Suplr_Mdcr_Stdzd_Amt_mean,Avg_Suplr_Mdcr_Stdzd_Amt_sum,Avg_Suplr_Mdcr_Stdzd_Amt_median,Avg_Suplr_Mdcr_Stdzd_Amt_std,Avg_Suplr_Mdcr_Stdzd_Amt_min,Avg_Suplr_Mdcr_Stdzd_Amt_max
0,1003000126,154.965761,1394.691851,85.053333,147.551365,20.000000,369.804068,47.053762,423.483862,21.348889,...,14.857500,28.362857,8.169091,72.843684,40.955161,368.596445,19.462308,34.424652,8.456364,89.597353
1,1003000480,272.003846,272.003846,272.003846,NaN,272.003846,272.003846,80.513846,80.513846,80.513846,...,64.407692,NaN,64.407692,64.407692,84.701538,84.701538,84.701538,NaN,84.701538,84.701538
2,1003000522,133.101129,266.202258,133.101129,122.893562,46.202258,220.000000,22.805968,45.611935,22.805968,...,18.243952,16.024522,6.912903,29.575000,19.471129,38.942258,19.471129,18.199332,6.602258,32.340000
3,1003000530,165.245147,1321.961175,52.694357,190.652061,8.582462,408.106667,35.321549,282.572391,8.476311,...,6.253973,30.757069,1.056667,67.595000,34.795433,278.363463,6.125764,42.309591,1.024167,90.520000
4,1003000597,11.385487,68.312921,8.053952,9.950240,0.390000,25.536875,5.845194,35.071166,4.867170,...,3.734386,3.520405,0.112054,8.331875,4.670143,28.020858,4.210925,3.984015,0.112054,9.864062

In [13]:
# Flag NPIs in the dataset that are listed in the LEIE exclusion list
npi_e = d["npi"]
npi_stats["Excluded"] = npi_stats['Rfrg_NPI'].isin(npi_e).map({True: "y", False: "n"})
npi_stats.head()

,Rfrg_NPI,Avg_Suplr_Sbmtd_Chrg_mean,Avg_Suplr_Sbmtd_Chrg_sum,Avg_Suplr_Sbmtd_Chrg_median,Avg_Suplr_Sbmtd_Chrg_std,Avg_Suplr_Sbmtd_Chrg_min,Avg_Suplr_Sbmtd_Chrg_max,Avg_Suplr_Mdcr_Alowd_Amt_mean,Avg_Suplr_Mdcr_Alowd_Amt_sum,Avg_Suplr_Mdcr_Alowd_Amt_median,...,Avg_Suplr_Mdcr_Pymt_Amt_std,Avg_Suplr_Mdcr_Pymt_Amt_min,Avg_Suplr_Mdcr_Pymt_Amt_max,Avg_Suplr_Mdcr_Stdzd_Amt_mean,Avg_Suplr_Mdcr_Stdzd_Amt_sum,Avg_Suplr_Mdcr_Stdzd_Amt_median,Avg_Suplr_Mdcr_Stdzd_Amt_std,Avg_Suplr_Mdcr_Stdzd_Amt_min,Avg_Suplr_Mdcr_Stdzd_Amt_max,Excluded
0,1003000126,154.965761,1394.691851,85.053333,147.551365,20.000000,369.804068,47.053762,423.483862,21.348889,...,28.362857,8.169091,72.843684,40.955161,368.596445,19.462308,34.424652,8.456364,89.597353,n
1,1003000480,272.003846,272.003846,272.003846,NaN,272.003846,272.003846,80.513846,80.513846,80.513846,...,NaN,64.407692,64.407692,84.701538,84.701538,84.701538,NaN,84.701538,84.701538,n
2,1003000522,133.101129,266.202258,133.101129,122.893562,46.202258,220.000000,22.805968,45.611935,22.805968,...,16.024522,6.912903,29.575000,19.471129,38.942258,19.471129,18.199332,6.602258,32.340000,n
3,1003000530,165.245147,1321.961175,52.694357,190.652061,8.582462,408.106667,35.321549,282.572391,8.476311,...,30.757069,1.056667,67.595000,34.795433,278.363463,6.125764,42.309591,1.024167,90.520000,n
4,1003000597,11.385487,68.312921,8.053952,9.950240,0.390000,25.536875,5.845194,35.071166,4.867170,...,3.520405,0.112054,8.331875,4.670143,28.020858,4.210925,3.984015,0.112054,9.864062,n

In [14]:
# Saving file
npi_stats.to_csv("/dsa/groups/casestudycf25/team02/DMEPOS_Amount_stats.csv",index=False)