## RBCS_Grouping

The purpose of this notebook is to create a dataset containing every unique combination of RBCS levels, ID and description, and HCPCS code and description.

This dataset is intended for inclusion in the final database.

End Result:

Saved the cleaned dataset to a shared team directory: /dsa/groups/casestudycf25/team02/DMEPOS_cleaned_grouping.csv

In [1]:
# Loading the required Libraries and Dataset
from pathlib import Path
import pandas as pd
df.to_csv("/dsa/groups/casestudycf25/team02/DMEPOS_RefPro_Ser_nar_clean.csv",index=False)

C:\Users\kamat\AppData\Local\Temp\ipykernel_11364\2566839318.py:5: DtypeWarning: Columns (11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"D:\DATA\Project\Current focus\DMEPOS - By Referral Provider and Service\DMEPOS_RefPro_Ser_clean.csv")

In [10]:
#Column names
df.columns

Index(['Year', 'Rfrg_NPI', 'Rfrg_Prvdr_Last_Name_Org', 'Rfrg_Prvdr_First_Name',
       'Rfrg_Prvdr_MI', 'Rfrg_Prvdr_Crdntls', 'Rfrg_Prvdr_Ent_Cd',
       'Rfrg_Prvdr_St1', 'Rfrg_Prvdr_St2', 'Rfrg_Prvdr_City',
       'Rfrg_Prvdr_State_Abrvtn', 'Rfrg_Prvdr_State_FIPS', 'Rfrg_Prvdr_Zip5',
       'Rfrg_Prvdr_RUCA_Cat', 'Rfrg_Prvdr_RUCA', 'Rfrg_Prvdr_Cntry',
       'Rfrg_Prvdr_Spclty_Cd', 'Rfrg_Prvdr_Spclty_Desc',
       'Rfrg_Prvdr_Spclty_Srce', 'RBCS_Lvl', 'RBCS_Id', 'RBCS_Desc',
       'HCPCS_CD', 'HCPCS_Desc', 'Suplr_Rentl_Ind', 'Tot_Suplrs',
       'DME_Sprsn_Ind', 'Tot_Suplr_Benes', 'Tot_Suplr_Clms', 'Tot_Suplr_Srvcs',
       'Avg_Suplr_Sbmtd_Chrg', 'Avg_Suplr_Mdcr_Alowd_Amt',
       'Avg_Suplr_Mdcr_Pymt_Amt', 'Avg_Suplr_Mdcr_Stdzd_Amt'],
      dtype='object')

In [18]:
# Selecting only 'RBCS_Lvl','RBCS_Id','RBCS_Desc','HCPCS_CD', 'HCPCS_Desc'
order = ['RBCS_Lvl','RBCS_Id','RBCS_Desc','HCPCS_CD', 'HCPCS_Desc']
rbcs_df = df[order]

In [19]:
# First few rows
rbcs_df.head()

,RBCS_Lvl,RBCS_Id,RBCS_Desc,HCPCS_CD,HCPCS_Desc
0,durable_medical_equipment,dc000n,dmeoxygen_and_supplies,e0431,portable_gaseous_oxygen_system_rental_includes...
1,durable_medical_equipment,dc002n,dmeoxygen_and_supplies,e1390,oxygen_concentrator_single_delivery_port_capab...
2,durable_medical_equipment,dd000n,dmewheelchairs,k0002,standard_hemi_low_seat_wheelchair
3,durable_medical_equipment,dd021n,dmewheelchairs,k0195,elevating_leg_rests_pair_for_use_with_capped_r...
4,durable_medical_equipment,dc002n,dmeoxygen_and_supplies,e1390,oxygen_concentrator_single_delivery_port_capab...

In [20]:
# Shape
rbcs_df.shape

(4413118, 5)

In [21]:
# Unique combinations of RBCS level, ID, description, and HCPCS code and description
unique_grouping = rbcs_df[['RBCS_Lvl','RBCS_Id','RBCS_Desc','HCPCS_CD','HCPCS_Desc']].drop_duplicates()

In [22]:
# First few rows
unique_grouping.head()

,RBCS_Lvl,RBCS_Id,RBCS_Desc,HCPCS_CD,HCPCS_Desc
0,durable_medical_equipment,dc000n,dmeoxygen_and_supplies,e0431,portable_gaseous_oxygen_system_rental_includes...
1,durable_medical_equipment,dc002n,dmeoxygen_and_supplies,e1390,oxygen_concentrator_single_delivery_port_capab...
2,durable_medical_equipment,dd000n,dmewheelchairs,k0002,standard_hemi_low_seat_wheelchair
3,durable_medical_equipment,dd021n,dmewheelchairs,k0195,elevating_leg_rests_pair_for_use_with_capped_r...
5,durable_medical_equipment,de017n,dmeother_dme,a4253,blood_glucose_test_or_reagent_strips_for_home_...

In [23]:
# Shape
unique_grouping.shape

(1267, 5)

In [24]:
# Saving file
unique_grouping.to_csv("/dsa/groups/casestudycf25/team02/DMEPOS_cleaned_grouping.csv", index=False)